huyto-atlanta.md
Hi all
I'm adding Atlanta to list of hometowns,
1. If you haven't been to Atlanta before -- what are you looking forward to?
2. If you have been to Atlanta -- what did you enjoy the most? Or the least?
3. What kind of food you like?
4. What is your favorite attractions?
=> huyto adds hometown of Atlanta 

DANSEWELL - Reno
Is this the right place to leave a comment on this?  NO.. It is not, this is a pull Request
What other types of Ice Cream have I left out?
What other locations for good ice-cream should be included?
Should we open a new project for Healthy People?
=> Dansewell   reno-(My Town)

cahn1-WDH.md
=> cahn1 adds hometown of cahn1-WDH

cahn1-WDH.md
Hi All! :hand: 
I'm proposing adding Woodland Hills to the list of hometowns, but I have some questions: 
1. If you haven't been to Woodland Hills before -- what are you looking forward to?
2. If you *have* been to Woodland Hills -- what did you enjoy the most? Or the least?
3. What kind of food does everyone like? I can make restaurant recommendations based on that.
4. Hey @crichiID -- what kinds of things does your sone like to do?
=> cahn1 added hometown of WDH - slightly modified with comments

KhaiMai2016-PlanoTX.md, YOUR_USERNAME-YOUR_TOWN.md
Hi all! 👋 
I'm proposing adding Orlando to the list of hometowns, but I have some questions:
1. If you haven't been to Orlando before -- what are you looking forward to?
2. If you *have* been to Orlando -- what did you enjoy the most? Or the least?
3. What kind of food does everyone like? I can make restaurant recommendations based on that.
4. Hey @crichID -- what kinds of things does your son like to do?
=> YOUR_USERNAME adds hometown of YOUR_HOMETOWN

michaelmsinclair-toronto.md
Oddly enough there are amusement parks around the city. Toronto isn't as dull as many people think.
Let's add Toronto to the the list of hometowns. 
Questions:
1. If you've never visited Toronto, will you visit soon?
2. If you *have* been to Toronto, what was the most memorable thing you saw or did there?
3. What's your favourite food? I'm sure we can find a restaurant that serves it.
=> MichaelMSinclair adds hometown of Toronto.

hemamanne-plano.md
Hi all 
I am proposing assing  Plano, TX to the list of Hometowns, but I have some questions:
1) If you haven't been to Plano before   -- What  are you looking forward to ?
2) If you have been  to Plano  - What did you enjoy the most? or least?
3)
=> hemamanne adds hometown of Plano

thirugnanamsubbiah-mountainview.md
Hi all,
I am proposing to add Mountain View to list of hometowns, but I have some questions
1. Q1
2. Q2
3. Q3 @huyto
=> thirugnanamsubbiah adds hometown of mountainview

ddiwakar-SanDiego.md
Hi All 😄 
Please provide your thoughts on adding San Diego in our hometown list.
Thanks
=> ddiwakar adds hometown of your San Diego

krvinod1-mv.md
Hi all, 👋
I am proposing adding Mountain View to the list of hometowns. Some activities to do in Mountain View
1) Hang out in downtown
2) Shoreline walk/biking/running
Thx
Vinod
=>  krvinod1-mv adds hometown of Mountain View

KhaiMai2016-PlanoTX.md, YOUR_USERNAME-YOUR_TOWN.md
Hello All,
1. hey @dbiscoIntuit 
2. Just want to say hi 👍
=> Khai mai2016 plano tx

trjnsteve-Tucson.md
Hello everyone :wave: 
I am proposing adding Tucson to the list of hometowns but I have some questions:
1. What time of year will you be coming to Tucson
2. Do you want indoor or outdoor activities
3. Do you Golf?
=> trjnsteve adds hometown of Tucson

ksreddy20-Mountain View.md
Request to add Los Angeles to the list.
=> ksreddy20 adding home town Mountain View.md

dbiscoIntuit-sanDiego.md
Hello 👋 
I'm proposing adding San Diego to the list of hometowns, but I have some questions:
1. If you haven't been to San Diego before -- what are you looking forward to?
2. If you _have_ been to San Diego -- what did you enjoy the most? Or the least?
3. What kind of food does everyone like? I can make restaurant recommendations based on that.
4. Hey @KhaiMai2016 -- what kinds of things does your sons like to do?
=> dbiscoIntuit adds hometown of San Diego

ccapurroroy-Reno.md#
Hello,
I'm proposing adding Reno, but I have a few questions:
1.  Which restaurants do you recommend?
2. @DanSewell  - What is your favorite Mexican restaurant in Sparks?
-- I forgot the name, but it is on Berring Blvd just outside of McCarran
=> ccapurroroy adds hometown of Reno

rakeshnrao-san_ramon.md
Hi all, 👋 
Add some text that you want to invite others for comments
San Ramon is awesome. You should visit at least once.
Rax
=> rakeshnrao adds hometown of San_Ramon

rajivhota24-San Diego.md
=> rajivhota24-San Diego.md

jimrmerritt-WHills.md
=> jimrmerritt adds hometown of WHills

cahn1-WDH.md
Hi All! ✋ 
I'm proposing adding Woodland Hills to the list of hometowns, but I have some questions:
1. If you haven't been to Woodland Hills before -- what are you looking forward to?
2. If you *have* been to Woodland Hills -- what did you enjoy the most? Or the least?
3. What kind of food does everyone like? I can make restaurant recommendations based on that.
4. Hey @crichiID -- what kinds of things does your son like to do?
=> cahn1 adds hometown of WDH

cahn1-WDH.md
Added restaurants and attractions
=> add restaurants and attractions to Los Angeles
